apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizzbuzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fizzbuzz
  template:
    metadata:
      labels:
        app: fizzbuzz
    spec:
      containers:
        - name: fizzbuzz
          image: fizzbuzz:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent